apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{name}}
  namespace: {{namespace}}
spec:
  rules:
    - host: {{domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{name}}-nginx
                port:
                  number: 80
