@Library('CIDD') _


genericBuildPipeline {

    useTemplate('rzm-lib-mvnw') {
        properties {
            validate = [
                checkstyle: [
                    enabled: true
                ]
            ]
            _package = [
                agentImage: 'ghcr.io/graalvm/native-image:ol8-java11-22.2.0'
            ]
        }
    }

    stages {
        _package {
            dockerBuild {
                imageName 'qa-templates/{{artifactId}}'
                dockerfileLocation './src/main/docker/Dockerfile'
                contextDir './target'
            }
        }

        install {
            dockerPush {
                imageName 'qa-templates/{{artifactId}}'
                registry 'docker-releases.internal.solidify.pl'
            }
        }
    }
}
